### PR TITLE
Adding MVE_EigenError to MVE enum

### PR DESCRIPTION
**Pull request by woodychow**
Or should I just use a general error code?

There are a bunch of asserts in Eigen. If we don't overload them with an exception, code will just crash silently.

### CODE REVIEW

**Comment by rdiankov** [comment]
having an exception that says MathError, or inverse matrix error, or possibly ContainerDetectionError is **much** better than EigenError... please rethink your exceptions.
thanks

**Comment by woodychow** [comment]
I have a hard time coming up with a good name for the exception. Sometimes Eigen asserts because of alignment issues, that is not exactly a math error. Also, the MujinCamera and MujinContainer classes can be used in places other than container detection as well. How about MVE_AssertError?

**Comment by liuhuanjim013** [comment]
maybe you can catch and throw to provide more context about the error. MVE_ContianerDetecitonError, MVE_DetectionError, etc can help achieve this

**Comment by woodychow** [comment]
I would really love to provide more context but I cannot. I am redefining the asserts inside the Eigen library. First of all, if I don't redefine the asserts, Eigen will just fail silently which is really bad. Second, the macro must be defined before the Eigen library is included.

What I can do is, redefine the assert with some dummy exception and catch and throw let's say MVE_ContianerDetecitonError. However, that requires putting try catch in all places using Eigen which is not very nice...

**Comment by liuhuanjim013** [comment]
in this case, maybe using the general MVE_Failed? the assertion failure will provide the filename and line number to give a hint

**Comment by woodychow** [comment]
That's totally fine by me. Rosen, are you OK with this?

**Comment by jerasman** [comment]
My 2 cents: MVE_EigenError or MVE_EigenAssertError seems the most adequate to me, since we are redefining (all) eigen asserts. Maybe Rosen has something else in mind.

**Comment by woodychow** [comment]
Well, I created a new EigenAssertException in visioncommon, and I am catching it in DetectContainer and throwing a new MVE_RecognitionError. This is not needed anymore. Thanks everyone.

**Pull request closed without merging**
